### ISSUE TITLE
Patrols only spawn one time

### ISSUE THREAD

**Issue by Wyqer** [Swiss-Sarge/SAR_AI#2]
If you enter a grid for the first time after server restart, the patrols spawn message appears in the server.rpt, the spots appear in ups debug on the map and the patrols are really there.
If you enter the same grid after you leaved it, it seems that the patrols are not really there. You have the patrol spawn message in the server.rpt and the dots with ups debug on the map. But I've searched in the grid about one hour (really) with a helicopter but nothing shoots on me or where visible. If i entered a "new" grid with the helicopter and searched for the groups shown at the ups debug on map i found them and they are shooting at me. Second time entered the same grid there are not there.
Is this the way you wanted it to work?

**Comment by Swiss-Sarge** [comment]
Nope, they should respawn when you enter.If you see UPS waypoint markers in the grid, and these are changing positions, groups must be there. I can recheck on my side. What i do is i search them with thermals, usually a lot faster. Or use a test grid, and spawn 10 groups. Keep in mind that there is a delay for them to despawn if you leave. But if you see them logged in the Array they should be there.

**Comment by Wyqer** [comment]
I'll check it again with some more groups, no problem. But maybe there is really an issue.
And the dots from ups debug are hopping around in the grid like hell. At the first enter of the grid the dots seem to move distances that are possible for people on foot, but second time it's really hopping around.

**Comment by Wyqer** [comment]
Again tested and no joy on chernarus and also lingor skaronator with spawning groups if you enter a grid after it was already "activated". Shown in UPS Debug on Map, hopping around from one corner to another in the grid, but nobody shooting or, as i can see, is on the ground.
Maybe there is some count issue with the $i variable? I'm only familiar with html, php, java and mysql and not with c++, but as i see the $i isn't set back to 0 after a spawning? Sorry if i just talking shit, but i really just want to help :).

**Comment by Swiss-Sarge** [comment]
could you post your rpt file with extreme debug enabled ? Thx a ton.

**Comment by Swiss-Sarge** [comment]
confirming the bug. i was able to reproduce on my Chernarus map. investigating now.

**Comment by Wyqer** [comment]
Still want a extreme debug rpt?

**Comment by Swiss-Sarge** [comment]
no thx. found the issue. upsmon is buggy. will upload a fix in a couple of mins

**Comment by Wyqer** [comment]
great man, i really look forward to it :)
